language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- make test
# deploy:
#   provider: pypi
#   username: "__token__"
#   on:
#     tags: true
#   skip_existing: true
#   skip_cleanup: true
#   password:
#     secure: TODO
